### PR TITLE
Fix: Modify retrieving path of Mechanical in tests

### PR DESCRIPTION
**Pull request by dipinknair**
Use `get_mechanical_path` instead of `find_mechanical` in `remote_session_launch` tests

### CODE REVIEW

**Comment by koubaa** [comment]
@dipinknair which issue is this associated with?

**Comment by dipinknair** [comment]
> @dipinknair which issue is this associated with?

Came across this issue while debugging remote_session_launch test failures locally. Since find_mechanical() does not check config.txt , some test were failing because of not able to retrieve path.

**Comment by koubaa** [comment]
@dipinknair we run on containers that put mechanical under /install/ansys_inc/vNnn.  So `find_mechanical` should work there. Do you know why it didn't?

**Comment by dipinknair** [comment]
> @dipinknair we run on containers that put mechanical under /install/ansys_inc/vNnn. So `find_mechanical` should work there. Do you know why it didn't?

This is to facilitate testing locally so that we can debug further issues that we see in tests. This is not a fix for the test failures but  fix to run the test locally since Pool test are also using find_mechanical.

**Comment by koubaa** [comment]
@dipinknair in that case I suggest leaving a fallback to find the path if there's nothing in the config, otherwise this will require setting the path before the test can run.

**Comment by dipinknair** [comment]
> @dipinknair in that case I suggest leaving a fallback to find the path if there's nothing in the config, otherwise this will require setting the path before the test can run.

get_mechanical_path takes care that and `find` arg set always true for this function which falls back to find mechanical if not path found from the config file

**Pull request merged**
